import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import { NextSvg } from "../constants/Svg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next.js Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Style>
        <nav className="title">
          <div className="logo">{NextSvg()}</div>
          <h1 className="name">Todo List</h1>
        </nav>
        <div className="contents">
          <div className="items">
            <div className="item">item</div>
            <div className="item">item</div>
            <div className="item">item</div>
            <div className="item">item</div>
          </div>
        </div>
      </Style>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const res = await fetch("https://api.github.com/repos/vercel/next.js");
  const json = await res.json();

  return {
    props: {
      stars: json.stargazers_count,
    },
  };
}

const Style = styled.main`
  height: 100vh;
  background-color: rgb(35, 39, 47);
  .title {
    display: flex;
    align-items: center;
    padding: 0 0 0 20px;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
    svg {
      height: 90px;
      fill: #ffffff;
    }

    .name {
      color: #ffffff;
      margin: 0 0 0 25px;
      font-size: 30px;
    }
  }

  .contents {
    margin: 30px 0 0;
    color: #ffffff;
    .items {
      display: flex;
      flex-direction: column;
      gap: 10px;
      .item {
        border-radius: 8px;
        padding: 10px;
        background-color: rgba(52, 58, 70);
      }
    }

    @media screen and (max-width: 640px) {
      padding: 0 20px 0;
    }

    @media (min-width: 640px) and (max-width: 960px) {
      padding: 0 48px 0;
    }
    @media (min-width: 960px) {
      padding: 0 48px 0;
    }
  }
`;
